[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ligotools"
version = "0.1.0"
description = "Helpers for Stat 159/259 LIGO tutorial (GW150914)"
requires-python = ">=3.9"
dependencies = []
